export const FETCH_CITIZEN = "FETCH_CITIZEN";
export const SHOW_ERROR = "SHOW_ERROR";
export const ADD_CITIZEN = "ADD_CITIZEN";
export const LOGOUT_CITIZEN = "LOGOUT_CITIZEN";
export const FETCH_PARTICIPATION_CITIZEN = "FETCH_PARTICIPATION_CITIZEN";
export const FETCH_ALL_PARTICIPATION_CITIZEN = "FETCH_ALL_PARTICIPATION_CITIZEN";

export const FETCH_ALL_TOWNS = "FETCH_ALL_TOWNS";

export const FETCH_ALL_EVENTS = "FETCH_ALL_EVENTS";
export const FETCH_EVENT = "FETCH_EVENT";

export const FETCH_ALL_PARTNERS = "FETCH_ALL_PARTNERS";
export const FETCH_PARTNER = "FETCH_PARTNER";

export const FETCH_DEAL_PARTNER = "FETCH_DEAL_PARTNER";
