export const FETCH_TOWN = "FETCH_TOWN";
export const SHOW_ERROR = "SHOW_ERROR";

export const FETCH_PARTNER_WAITING = "FETCH_PARTNER_WAITING";
export const FETCH_PARTNER_ACCEPTED = "FETCH_PARTNER_ACCEPTED";
export const ACCEPT_PARTNER = "ACCEPT_PARTNER"; 
export const REFUSE_PARTNER = "REFUSE_PARTNER";

export const FETCH_EVENT_WAITING = "FETCH_EVENT_WAITING";
export const FETCH_EVENT_ACCEPTED = "FETCH_EVENT_ACCEPTED";
export const ACCEPT_EVENT = "ACCEPT_EVENT";
export const REFUSE_EVENT = "REFUSE_EVENT";

export const FETCH_CITIZENS = "FETCH_CITIZENS";